config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end

  root to: 'pages#home'

  resources :items do
    resources :bookings
  end

     resources :bookings, only: [:destroy] do
      resources :reviews, only: [:new, :create, :show]
  end

  # resources :items do
  #   resources :reviews, only: [:new, :create]
  # end

  # resources :items do
  #   resources :item_categories
  # end

  get '/dashboard', to: 'pages#dashboard'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :review, dependent: :destroy
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end



# Thanks to => https://medium.com/@sonia.montero/date-validations-and-flatpickr-setup-for-rails-24c78d6eb784

app/models/category.rb
class Category < ApplicationRecord
  CATEGORIES = ['Casual', 'Daytime', 'Date Night', 'Work', 'Maternity', 'Everything']
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  has_one_attached :photo

  # has_many :item_categories, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, :through => :bookings, dependent: :destroy
  # has_many :categories, through: :item_categories
  validates :name, presence: true
  validates :size, presence: true
  validates :price, presence: true
  validates :description, presence: true

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  has_one :item, :through => :booking
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :items
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :make_booking, only: [:show, :edit, :update, :destroy]

  def new
    @item = Item.find(params[:item_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @item = Item.find(params[:item_id])
    @booking = Booking.new(booking_params)
    @booking.item = @item
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to item_booking_path(@item, @booking)
    else
      render new
    end
  end

  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def show
    @item = @booking.item
  end

  def edit
    @item = Item.find(params[:item_id])
  end

  def update
    @item = Item.find(params[:item_id])
    if @booking.update(booking_params)
    redirect_to item_booking_path
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    flash[:alert] = "Your current booking was cancelled"
    redirect_to root_path
  end

  private

  def make_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  def new
    @item = Item.find(params[:item_id])
    @item_category = ItemCategory.new
    authorize @item
  end

  def create
    @item = Item.find(params[:item_id])
    category_ids = params[:item_category][:category_id]
    authorize @item
    category_ids.each do |category_id|
    @item_category = ItemCategory.new(item_id: @item.id, category_id: category_id)
    @item_category.save
  end

  redirect_to item_path(@item)
  end

  private

  def item_category_params
    params.require(:item_category).permit(:category_item)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :make_item, only: [:show, :edit, :update, :destroy]
    def index
      # @items = Item.all
      @items = policy_scope(Item).order(created_at: :desc)
    end

    def show

    end

    def new
      @item = Item.new
      authorize @item
      @category = Category.new
    end

    def create
      @item = Item.new(item_params)
      @item.user = current_user
      authorize @item
      @category = Category.new
      if @item.save
        redirect_to item_path(@item)
        flash[:alert] = 'You have successfully added your item.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @item.update(item_params)
        redirect_to item_path(@item) and return
      else
        render :edit
      end
    end

    def destroy
      @item.destroy
      flash[:alert] = 'You have successfully deleted your item.'
      redirect_to dashboard_path and return
    end

    private

    def make_item
      @item = Item.find(params[:id])
      authorize @item
    end

    def item_params
      params.require(:item).permit(:name, :price, :size, :description, :photo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def dashboard
    @user = current_user
    #All bookings made by user, present and past
    @user_bookings = Booking.where(user_id: @user.id)
    @user_past_bookings = []
    @user_past_bookings_hash = {}
    @user_current_bookings = []
    @user_current_bookings_hash = {}
    @my_items_booked_hash = {}

    # My bookings in progress && My past bookings
    @user_bookings.each do | booking |
      if booking.end_date < Time.now + 1.day
        @user_past_bookings << booking
        @user_past_bookings_hash["#{booking.id}"] = Item.where(id: booking.item_id)
      else
        @user_current_bookings << booking
        @user_current_bookings_hash["#{booking.id}"] = Item.where(id: booking.item_id)
      end
    end


    #All my items that are booked by other users
    @my_items_booked = Booking.joins(:item).where("items.user_id" => current_user.id)
    @my_items_booked.each do | booking |
      @my_items_booked_hash["#{booking.id}"] = Item.where(id: booking.item_id)
    end
    # authorize @user
  end

  def home
    @categories = Category.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_booking, only: [:new, :create]

  def new
    @review = Review.new
    # @booking = Booking.find(params[:booking_id])
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    @item = @booking.item
    @review.user = current_user
    authorize @item
    if @review.save
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div id='item-booking-dates' data-unavailable="<%= @item.unavailable_dates.to_json %>">
    <% if current_user.id != @item.user_id  %>
    <%= simple_form_for [@item, @booking] do |t| %>
      <%= t.input :start_date, as: :string, required: :true, input_html: { id: "booking_start_date" } %>
      <%= t.input :end_date, as: :string, required: :true, input_html: { id: "booking_end_date" } %>
      <%= t.submit "Confirm Your Booking", class: "button bookingconfirm" %>
    <% end %>
  <% end %>
  <%= link_to "Back to Items", items_path, class: "button bookingback" %>
</div>

app/views/bookings/edit.html.erb
<div class="container">
  <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
    <h1>Edit Your Booking for <%=  @item.name %> </h1>
      <%= render 'form', item: @item %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="col-4 offset-4 mt-5 form h-50">
    <div class="mx-auto">
        <h1> Booking for <%=  @item.name %> </h1>
        <%= render 'form', item: @item %>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="col-6 offset-3 mt-5 h-50">
    <div class="card mb-3" style="min-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <% if @item.photo.attached? %>
                <%= cl_image_tag @item.photo.key, height: 800, width: 400, crop: :fit, class: "card-image" %>
                <% else %>
                <p>Oops! This item doesn't have an image!</p>
                <% end %>
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <div class="row">
                        <div class="col-8">
                            <h5 class="card-title">Thanks for booking <%= @item.name %></h5>
                        </div>
                        <div class="col-4 pl-5">
                            <%= link_to image_tag('edit.svg', class: "auth-icon edit mr-2"), edit_item_booking_path %>
                            <%= link_to image_tag('delete.svg', class: "auth-icon delete"), item_booking_path(@booking), method: :delete %>
                        </div>
                    </div>
                    <p class="card-text">From: <%= @booking.start_date.strftime('%m/%d/%Y') %></p>
                    <p class="card-text">To: <%= @booking.end_date.strftime('%m/%d/%Y') %></p>
                    <%= link_to "Continue shopping", items_path, class: "button rent" %>
                    <%= link_to "My dashboard", dashboard_path, class: "button confirm" %>
                </div>
            </div>
        </div>
    </div>

app/views/item_categories/new.html.erb
<div class="col-6 offset-3 mt-5">
    <%= simple_form_for([@item, @item_category]) do |f| %>
    <%= f.association :category, input_html: { multiple: true, class: "multiple-select" }, include_hidden: false %>
    <%= f.button :submit, "Add Category", class: "button" %>
    <% end %>
</div>

app/views/items/_form.html.erb
<%= simple_form_for item do |c| %>
<%= c.input :name, label: false %>
<%= c.input :size, label: false %>
<%= c.input :price, label:false %>
<%= c.input :description, label:false %>
<%= c.input :photo, as: :file, label:false %>
<%= c.submit "#{item.id ? "Edit" : "Add" } Item", class: "button bookingconfirm" %>
<% end %>

app/views/items/edit.html.erb
<div class="col-6 mt-5 offset-3">
    <%= render 'form', item: @item %>
</div>

app/views/items/index.html.erb
<div class="row mt-5 mr-5 pl-2 ml-auto">
    <div class="col-12">
        <% if policy(Item).new? %>
        <%= link_to 'Add New Item', new_item_path, class: 'button rent' %>
        <%end%>
    </div>
</div>
<div class="row row-cols-6 mt-5 ml-5 pl-4">
    <% @items.each do |item| %>
    <div class="col mr-5 mb-5 item">
        <div class="d-flex flex-column">
            <div class="item-image">
                <% if item.photo.attached? %>
                <%= cl_image_tag item.photo.key, height: 800, width: 400, crop: :fit, class: "image" %>
                <% else %>
                <p class="text-center">Oops! This item doesn't have an image!</p>
                <% end %>
            </div>
            <div class="item-content h-25 py-3">
                <div class="d-flex justify-content-between">
                    <p class="text-muted item-name"><%= item.name %></p>
                    <span class="item-price"><%= item.price %>AUD</span>
                </div>
                <%= link_to 'Show', item_path(item), class: 'button show' %>
            </div>
        </div>
    </div>
    <%end%>
</div>

app/views/items/new.html.erb
<div class="col-6 mt-5 offset-3">
    <%= render 'form', item: @item %>
</div>

app/views/items/show.html.erb
<div class="col-5 ml-5 mt-5 mr-2 show-image-container">
    <% if @item.photo.attached? %>
    <%= cl_image_tag @item.photo.key, height: 800, width: 400, crop: :fit %>
    <% else %>
    <p class="ml-3"><strong>Oops! This item doesn't have an image!</strong></p>
    <% end %>
</div>
<div class="col-6 mt-5 show-item-container  border-left">
    <div class="row">
        <div class="col-12">
            <h1><%= @item.name %></h1>
            <p class="text-muted"><%= @item.description %></p>
            <p class="text-muted"><%= @item.price %> AUD</p>
        </div>
    </div>
    <div class="row">
        <div class="col-12 pl-3 mt-5">
            <h6>SIZE</h6>
            <% ["XS","S","M","L","XL"].each do |size| %>
            <% if size.eql?(@item.size)%>
            <span class="badge bg-secondary"><%= size%></span>
            <%else %>
            <span class="badge bg-dark"><%= size%></span>
            <%end%>
            <%end%>
        </div>
    </div>
    <div class="row mt-5">
        <% if current_user.id != @item.user_id %>
        <div class="col-6 pt-3">
            <%= link_to "Rent", new_item_booking_path(@item), class: "button review" %>
        </div>
        <%else%>
        <div class="col-6 pt-3">
            <%= link_to "Edit", edit_item_path(@item), class: "button edit" %>
            <%= link_to "Delete", item_path(@item), method: :delete, class: "button delete" %>
        </div>
        <% end %>
    </div>
    <div class="row mt-5">
        <div class="col">
            <h2>Reviews</h2>
        </div>
    </div>
    <div class="row mt-5">
        <% if @item.reviews.exists? %>
        <div class="d-flex flex-column ml-3">
            <% @item.reviews.each do |review| %>
            <div class="d-flex">
                <%review.rating.times do%>
                <i class="fas fa-star"></i>
                <%end%>
            </div>
            <p> - <%= review.content %></p>
            <% end %>
        </div>
        <% else %>
        <p class="align-self-center">This item has no reviews</p>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Fashionista</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
</head>

<body>
    <div class="container-fluid page-container">
        <div class="row">
            <div class="col-12">
                <%= render "shared/navbar" %>
            </div>
        </div>
        <div class="row">
            <% if current_user %>
            <div class="col-3 ml-5">
                <h6>Welcome, <%= current_user.email %>!</h6>
            </div>
            <% end %>
        </div>
        <% if controller_name == "sessions" || controller_name == "registrations" %>
        <div class="row flex-grow-1 h-25">
            <%else%>
            <div class="row flex-grow-1 h-100">
                <%end%>
                <%= yield %>
                <div class="col-3">
                    <% if !notice.nil? %>
                    <p class="notice"><%= notice %></p>
                    <% end %>
                    <% if !alert.nil? %>
                    <p class="alert"><%= alert %></p>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

app/views/pages/dashboard.html.erb
<div class="row ml-5 mt-5 h-50">
    <div class="col-12 mb-4">
        <%= link_to "Rent clothes", items_path, class: "button review rent" %>
    </div>
    <div class="card mb-3" style="min-width: 20rem;">
        <div class="card-header d-flex justify-content-between">
            <h6>Current bookings: Clothes I rented</h6>
        </div>
        <div class="card-body">
            <% if @user_current_bookings.present? %>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Booking ID#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Start date</th>
                        <th scope="col">End date</th>
                    </tr>
                </thead>
                <tbody>
                    <% @user_current_bookings.each do |booking| %>
                    <tr>
                        <th scope="row"><%= booking.id %></th>
                        <td><%= @user_current_bookings_hash["#{booking.id}"][0].name %></td>
                        <td><%= @user_current_bookings_hash["#{booking.id}"][0].price %> AUD</td>
                        <td><%= booking.start_date.strftime('%m/%d/%Y') %></td>
                        <td><%= booking.end_date.strftime('%m/%d/%Y') %></td>
                    </tr>
                    <%end%>
                </tbody>
            </table>
            <% else %>
            <p>You do not have any current bookings</p>
            <% end %>
        </div>
    </div>
    <div class="card mb-3" style="min-width: 25rem;">
        <div class="card-header d-flex justify-content-between">
            <h6>Past bookings: Clothes I rented</h6>
        </div>
        <div class="card-body">
            <% if @user_past_bookings.present? %>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Booking ID#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Start date</th>
                        <th scope="col">End date</th>
                    </tr>
                </thead>
                <tbody>
                    <% @user_past_bookings.each do |booking| %>
                    <tr>
                        <th scope="row"><%= booking.id %></th>
                        <td><%= @user_past_bookings_hash["#{booking.id}"][0].name %></td>
                        <td><%= @user_past_bookings_hash["#{booking.id}"][0].price %> AUD</td>
                        <td><%= booking.start_date.strftime('%m/%d/%Y') %></td>
                        <td><%= booking.end_date.strftime('%m/%d/%Y') %></td>
                        <td><%= link_to "Add a review", new_booking_review_path(booking), class: "link" %></td>
                    </tr>
                    <%end%>
                </tbody>
            </table>
            <% else %>
            <p>You do not have any previous bookings</p>
            <% end %>
        </div>
    </div>
    <div class="card mb-3" style="min-width: 20rem;">
        <div class="card-header d-flex justify-content-between">
            <h6>Bookings: Clothes I posted for rent </h6>
        </div>
        <div class="card-body">
            <% if @my_items_booked.present? %>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Booking ID#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Start date</th>
                        <th scope="col">End date</th>
                    </tr>
                </thead>
                <tbody>
                    <% @my_items_booked.each do |booking| %>
                    <tr>
                        <th scope="row"><%= booking.id %></th>
                        <td><%= @my_items_booked_hash["#{booking.id}"][0].name %></td>
                        <td><%= @my_items_booked_hash["#{booking.id}"][0].price %> AUD</td>
                        <td><%= booking.start_date.strftime('%m/%d/%Y') %></td>
                        <td><%= booking.end_date.strftime('%m/%d/%Y') %></td>
                    </tr>
                    <%end%>
                </tbody>
            </table>
            <% else %>
            <p>You have not uploaded any clothing items</p>
            <% end %>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="col-3">
    <%= render 'shared/category-grid', categories: @categories %>
</div>
<div class="col-9 background-image">
</div>

app/views/reviews/new.html.erb
<div class="col-6 mt-5 offset-3">
    <%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :content, placeholder: 'Rate your experience' %>
    <%= f.input :rating, collection: (0..5) %>
    <%= f.submit "Submit", class: "button" %>
    <% end %>
</div>

app/views/shared/_category-grid.html.erb
<div class="row row-cols-3 gx-3 ml-5 margin-top">
    <% categories.each do |category| %>
    <div class="col m-3 tile rounded shadow d-flex flex-column justify-content-around align-items-center">
        <%= image_tag(category.image, class: "w-50") %>
        <div class="tile_text"><%= category.name %></div>
    </div>
    <%end %>
</div>

app/views/shared/_logo.html.erb
<div class="logo-text ml-2">
    <%= link_to "fashionista.", items_path %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon pt-3 pl-5 w-100">
    <%= link_to "fashionista.", items_path, class: "logo-text" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if current_user.nil? %>
            <li class="nav-item">
                <%= link_to image_tag('woman.svg', class: 'auth-icon'), new_user_session_path %>
            </li>
            <% else %>
            <li class="d-flex justify-content-between nav-item active">
                <%= link_to "Clothes", items_path, class: "nav-link effect-underline" %>
                <%= link_to "Dashboard", dashboard_path, class: "nav-link effect-underline" %>
                <%= link_to image_tag('logout.svg', class: 'auth-icon logout ml-5'), destroy_user_session_path, method: :delete %>
            </li>
        </ul>
        <% end %>
    </div>
</div>